name: Build Plugin

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/build.yaml@master
    with:
      dotnet-version: "9.0.x"
      dotnet-target: "net9.0"
